spring.application.name=TicTacToe
server.port=8080
spring.data.mongodb.database=TicTacToeRecords
spring.data.mongodb.uri=mongodb+srv://parthib:12345@cluster1.ycmntea.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1
